<?php

/**
 * Parse a new "http methods" key coming from a hook_menu() menu item.
 *
 * @code
 * $items['api/users/%/%'] = array(
 *   'http methods' => array('GET'),
 *   'access arguments' => array('access content'),
 *   'page arguments' => array(2, 3),
 *   'page callback'    => 'api_users',
 * );
 * @endcode
 *
 * simplewebservice module will catch all menu item with a "webservice" key and send them to
 * a custom page callback : simplewebservice_page_callback
 *
 * This page callback is used as a common wrapper for all webservices; this page callback
 * will then call with call_user_func()the original page callback you have declared in your hook menu.
 */

/**
 * Implements hook_menu_alter()
 * @param $items
 */
function simplewebservice_menu_alter(&$items) {

  // search for menu items declaring a "webservice" key, and change their page callback
  // by our custom simplewebservice page callback.
  foreach ($items as $id => $item) {
    if (!empty($items[$id]['http methods'])) {
      if (empty($items[$id]['format']) || $items[$id]['format'] == 'json') {
        $items[$id]['theme arguments'] = array(
          'http methods' => $items[$id]['http methods'],
          'page callback' =>  $items[$id]['page callback'],
        );
        $items[$id]['delivery callback'] = 'simplewebservice_delivery_json_callback';
      }
    }
  }

}

/**
 * Special menu page callback for wrapping simplewebservices hook menu items.
 */
function simplewebservice_delivery_json_callback() {

  $router_item = menu_get_item();

  if (!in_array($_SERVER['REQUEST_METHOD'], $router_item['theme_arguments']['http methods'])) {
    drupal_json_output(array('errors' => array('http method not allowed')));
    drupal_exit();
  }

  // make sur we accept external http requests.
  header('Content-Type', 'application/json');
  header('Access-Control-Allow-Origin: *');
  header('Access-Control-Allow-Methods: GET, POST, OPTIONS');
  header('Access-Control-Allow-Headers: Origin, Content-Type, Accept, Authorization, X-Request-With');
  header('Access-Control-Allow-Credentials: true');

  $callback = str_replace("%method", $_SERVER['REQUEST_METHOD'], $router_item['theme_arguments']['page callback']);
  $response = call_user_func_array($callback, $router_item['page_arguments']);

  drupal_alter('simplewebservice_response', $response);

  $json = drupal_json_encode($response);

  // put files in cache.
  /*if ($_SERVER['REQUEST_METHOD'] == 'GET') {

    if (!is_writable('api')) {
      print 'api' . ' is not writable';exit;
    }
    $href_array = explode('/', $router_item['href']);
    array_pop($href_array);
    $filepath = implode(DIRECTORY_SEPARATOR, $href_array);
    @mkdir($filepath, 0775, TRUE);
    file_put_contents($router_item['href'], $json);

  }
  */
  echo $json;
  drupal_exit();
}

function get_datas_from_json_post_request() {
  $http_body = file_get_contents("php://input");
  $values = json_decode($http_body);
  return $values;
}






