<?php
/**
 * Parse a new "webservice" key coming from a hook_menu() menu item.
 * You have to define your hook_menu as usual, simply add a "webservice" key, that allow
 * to describe some additionnals behaviors for those special menu items.
 *
 * @code
 * $items['api/users/%/%'] = array(
 *   'http methods' => array('GET'),
 *   'access arguments' => array('access content'),
 *   'page arguments' => array(2, 3),
 *   'page callback'    => 'api_users',
 * );
 * @endcode
 *
 * simplewebservice module will catch all menu item with a "webservice" key and send them to
 * a custom page callback : simplewebservice_page_callback
 *
 * This page callback is used as a common wrapper for all webservices; this page callback
 * will then call with call_user_func()the original page callback you have declared in your hook menu.
 */

/**
 * Implements hook_menu_alter()
 * @param $items
 */
function simplewebservice_menu_alter(&$items) {

  // search for menu items declaring a "webservice" key, and change their page callback
  // by our custom simplewebservice page callback.
  foreach ($items as $id => $item) {
    if (!empty($items[$id]['http methods'])) {
      if (empty($items[$id]['format']) || $items[$id]['format'] == 'json') {
        $items[$id]['theme arguments'] = array(
          'http methods' => $items[$id]['http methods'],
          'page callback' =>  $items[$id]['page callback'],
        );
        $items[$id]['delivery callback'] = 'simplewebservice_page_json_callback';
        //$items[$id]['page callback'] = 'simplewebservice_page_json_callback';
      }
      else {
        $items[$id]['page callback'] = 'simplewebservice_page_unknwon_callback';
      }
    }
  }

}

function simplewebservice_delivery_json_callback($result) {
  header('Access-Control-Allow-Origin: *');
  header('Access-Control-Allow-Headers: Origin, X-Requested-With, Content-Type, Accept');
  drupal_json_output($result);
  drupal_exit();
}

/**
 * Special menu page callback for wrapping simplewebservices hook menu items.
 */
function simplewebservice_page_json_callback() {

  $router_item = menu_get_item();

  if (!in_array($_SERVER['REQUEST_METHOD'], $router_item['theme_arguments']['http methods'])) {
    drupal_json_output(array('errors' => array('http method not allowed')));
    drupal_exit();
  }

  // make sur we accept external http requests.
  header('Access-Control-Allow-Origin: *');
  header('Access-Control-Allow-Methods: GET, POST, OPTIONS');
  header('Access-Control-Allow-Headers: Origin, Content-Type, Accept, Authorization, X-Request-With');
  header('Access-Control-Allow-Credentials: true');

  $callback = str_replace("%method", $_SERVER['REQUEST_METHOD'], $router_item['theme_arguments']['page callback']);
  $response = call_user_func_array($callback, $router_item['page_arguments']);

  drupal_json_output($response);
  drupal_exit();

}

function get_datas_from_json_post_request() {
  $http_body = file_get_contents("php://input");
  $values = json_decode($http_body);
  return $values;
}

function simplewebservice_page_unknwon_callback() {
  return "Unknown page callback";
}
