<?php
/**
 * http://jsonapi.org/
 */

/**
 * Implements hook_menu
 */
function ionic_menu() {
  $items['api/users'] = array(
    'http methods' => array('GET'),
    'access arguments' => array('access content'),
    'page callback'    => '%method_api_users',
  );
  $items['api/users/%'] = array(
    'http methods' => array('GET'),
    'access arguments' => array('access content'),
    'page arguments' => array(2),
    'page callback'    => '%method_api_users_detail',
  );
  return $items;
}

function GET_api_users() {
  $query = db_select('users', 'u');
  $query->addField('u', 'uid');
  $query->condition('status', 1);
  $users_datas = $query->execute()->fetchAll();
  $users = array();
  foreach ($users_datas as $i => $user_datas) {
    $user = user_load($user_datas->uid);
    $users[$i]['uid'] = $user->uid;
    $users[$i]['mail'] = $user->mail;
    $users[$i]['name'] = $user->name;
    if ($user->picture) {
      $users[$user->uid]['picture'] = file_create_url($user->picture->uri);
    }
    else {
      $users[$i]['picture'] = '';
    }
  }
  return array(
    'data' => $users
  );
}

function GET_api_users_detail($uid) {
  $user = user_load($uid);
  if (!$user) {
    return array(
      'errors' => array('No user found with this id.'),
      'data' => array(),
    );
  }
  return array(
    'data' => array(
      'uid' => check_plain($user->uid),
      'name' => check_plain($user->name),
      'mail' => check_plain($user->mail),
    ),
  );
}